apiVersion: v1
kind: Secret
metadata:
  name: assets-secret
type: Opaque
data:
  azurestorageaccountname: XXXX
  azurestorageaccountkey: YYYY
---
apiVersion: v1
kind: Service
metadata:
  name: landing-service
spec:
  type: LoadBalancer
  ports:
  - name: http-landing
    protocol: TCP
    port: 80
    targetPort: 80
  - name: http-fe
    protocol: TCP
    port: 90
    targetPort: 90
  selector:
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-deployment
spec:
  selector:
    matchLabels:
      app: landing-app
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: landing-app
        tier: frontend
    spec:
      containers:
      - name: landing
        image: mearsk.azurecr.io/landing:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: azure-fs
            mountPath: /var/www/html/assets/external
      volumes:
      - name: azure-fs
        azureFile:
          secretName: assets-secret
          shareName: kubernetes-assets
          readOnly: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-fe
spec:
  selector:
    matchLabels:
      app: appappa
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: appappa
        tier: frontend
    spec:
      containers:
      - name: mr-business
        image: mearsk.azurecr.io/mr-business:latest
        ports:
        - containerPort: 90
        volumeMounts:
          - name: azure-fs
            mountPath: /var/www/html/assets/external
      volumes:
      - name: azure-fs
        azureFile:
          secretName: assets-secret
          shareName: kubernetes-assets
          readOnly: false