FROM debian:latest
RUN apt-get update
RUN apt-get install -y nginx
ADD nginx.conf /etc/nginx/
ADD web usr/share/nginx/html
ADD web var/www/html
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
EXPOSE 90
CMD service nginx start